# Generated by Django 2.2.6 on 2019-12-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbcampaign', '0017_auto_20191218_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_campaignid', models.IntegerField()),
                ('campaign_title', models.CharField(max_length=48)),
                ('campaign_status', models.CharField(max_length=16)),
            ],
        ),
    ]
