# Generated by Django 2.2.6 on 2019-12-30 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbcampaign', '0018_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='campaign_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fbcampaign.Campaign'),
        ),
    ]
